### ISSUE TITLE
De que forma posso executar o app ?

### ISSUE THREAD

**Issue by alexjosesilva** [fhugoduarte/rn-WhoIsThisPokemon#1]
Quais os passos necessários para executar o app ?

**Comment by RodrigoPauletti** [comment]
@alexjosesilva Aqui tem o passo a passo da instalação do React Native
https://facebook.github.io/react-native/docs/getting-started.html

**Comment by alexjosesilva** [comment]
Esta ocorrendo erros durante a execução. Qual tua versão do android ?

**Comment by RodrigoPauletti** [comment]
@alexjosesilva Posta aqui os erros que estão ocorrendo.
No momento não estou com nenhum emulador instalado, mas quando testei, foi pelo Genymotion e funcionou no emulador do Samsung Galaxy S8 sem nenhum problema.

**Comment by alexjosesilva** [comment]
λ react-native run-android
info JS server already running.
info Building and installing the app on the device (cd android && gradlew.bat app:installDebug)...

> Configure project :app
Observed package id 'platforms;android-23' in inconsistent location 'C:\Users\sulwork01\AppData\Local\Android\Sdk\platforms\android-23' (Expected 'C:\Users\sulwork01\AppData\Local\Android\Sdk\platforms\platforms\android-23')
Observed package id 'platforms;android-28' in inconsistent location 'C:\Users\sulwork01\AppData\Local\Android\Sdk\platforms\android-28' (Expected 'C:\Users\sulwork01\AppData\Local\Android\Sdk\platforms\platforms\android-28')
Observed package id 'platforms;android-29' in inconsistent location 'C:\Users\sulwork01\AppData\Local\Android\Sdk\platforms\android-29' (Expected 'C:\Users\sulwork01\AppData\Local\Android\Sdk\platforms\platforms\android-29')
Observed package id 'platforms;android-23' in inconsistent location 'C:\Users\sulwork01\AppData\Local\Android\Sdk\platforms\android-23' (Expected 'C:\Users\sulwork01\AppData\Local\Android\Sdk\platforms\platforms\android-23')
Observed package id 'platforms;android-28' in inconsistent location 'C:\Users\sulwork01\AppData\Local\Android\Sdk\platforms\android-28' (Expected 'C:\Users\sulwork01\AppData\Local\Android\Sdk\platforms\platforms\android-28')
Observed package id 'platforms;android-29' in inconsistent location 'C:\Users\sulwork01\AppData\Local\Android\Sdk\platforms\android-29' (Expected 'C:\Users\sulwork01\AppData\Local\Android\Sdk\platforms\platforms\android-29')
Checking the license for package Android SDK Build-Tools 28.0.3 in C:\Users\sulwork01\AppData\Local\Android\Sdk\platforms\licenses
Warning: License for package Android SDK Build-Tools 28.0.3 not accepted.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Failed to install the following Android SDK packages as some licences have not been accepted.
     build-tools;28.0.3 Android SDK Build-Tools 28.0.3
  To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
  Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html

  Using Android SDK: C:\Users\sulwork01\AppData\Local\Android\Sdk\platforms

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s

**Comment by alexjosesilva** [comment]
não entendi esse erro

**Comment by alexjosesilva** [comment]
estou usando android 9 e 6...porem não funcionou ?

**Comment by RodrigoPauletti** [comment]
@alexjosesilva Você está emulando? Se sim, executou todos os comandos necessários?
Aqui tem um tutorial passo-a-passo da Rocketseat para configurar corretamente sua emulação: https://docs.rocketseat.dev/ambiente-react-native/android/emulador

**Comment by alexjosesilva** [comment]
estou usando o emulador Android

**Comment by alexjosesilva** [comment]
![image](https://user-images.githubusercontent.com/246117/61325541-60851b80-a7eb-11e9-9092-e7c1d50740f5.png)

**Comment by alexjosesilva** [comment]
Esta aparecendo este erro aqui !

**Comment by alexjosesilva** [comment]
![image](https://user-images.githubusercontent.com/246117/61337617-866ee800-a80c-11e9-8e67-3b5268fe0f35.png)

**Comment by alexjosesilva** [comment]
![image](https://user-images.githubusercontent.com/246117/61337732-fda47c00-a80c-11e9-8f0a-dae3b89a8ff0.png)

**Comment by alexjosesilva** [comment]
![image](https://user-images.githubusercontent.com/246117/61337764-12810f80-a80d-11e9-8dc8-876becb3dda5.png)

**Comment by alexjosesilva** [comment]
Loading dependency graph, done.
error: bundling failed: ReferenceError: Unknown helper objectSpread2
    at loadHelper

**Comment by alexjosesilva** [comment]
react-native-cli: 2.0.1
react-native: 0.59.9

**Comment by alexjosesilva** [comment]
corrigir.....apaguei a pasta  node_modules
e reinstalei com npm install
e restarte o package.json
com npm start

**Comment by alexjosesilva** [comment]
![image](https://user-images.githubusercontent.com/246117/61339262-51b25f00-a813-11e9-9333-6c8c9b4154c8.png)
